language: python

python:
  - 2.7
  - 3.4

env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10

install:
 - "git clone git://github.com/n1k0/casperjs.git"
 - "sudo ln -s `pwd`/casperjs/bin/casperjs /usr/local/bin"
 - pip install argparse  # This is a dependency of our Django test script
 - pip install -q Django==$DJANGO_VERSION
 - pip install mock
 - pip install flake8 coverage
 - pip install django-timedeltafield

before_script:
    - flake8 --ignore=E501 screamshot

script:
    - coverage run quicktest.py screamshot

after_success:
 - pip install coveralls
 - coveralls
